### ISSUE TITLE
Sometimes scales up to many more workers than jobs

### ISSUE THREAD

**Issue by jonnor** [the-grid/guv#94]
With very tight/agressive deadlines compared to processing characteristics, have seen that say for
3 jobs scaling calculates 20 workers (or hits max for some other reason). This does not make sense`*`, as 20 workers cannot do the complete 3 jobs any faster than 3 workers could.

`*` however, a high number of jobs are also a signal of 'lots of work' so we likely do want to overcommit a bit, say possibly up to a factor of 2.

**Comment by jonnor** [comment]
This config with 1 job should reproduce it - scaled to 2 workers.

```
imgflo_video:
  deadline: 1200
  percentile: 68
  app: imgflo
  queue: imgflo_video.JOB
  min: 0
  max: 2
  dynosize: 2x
  concurrency: 4
  processing: 496.1561666666667
  stddev: 1404.0504969888714
```
